import Vue from 'vue'

Vue.component('action-selector', require('@/components/ActionSelector'))
Vue.component('card', require('@/components/Card'))
Vue.component('checkbox', require('@/components/Index/Checkbox'))
Vue.component('confirm-action-modal', require('@/components/Modals/ConfirmActionModal'))
Vue.component(
    'confirm-upload-removal-modal',
    require('@/components/Modals/ConfirmUploadRemovalModal')
)
Vue.component('create-resource-button', require('@/components/CreateResourceButton'))
Vue.component('delete-menu', require('@/components/DeleteMenu'))
Vue.component('delete-resource-modal', require('@/components/Modals/DeleteResourceModal'))
Vue.component('dropdown', require('@/components/Dropdown'))
Vue.component('dropdown-menu', require('@/components/DropdownMenu'))
Vue.component('dropdown-trigger', require('@/components/DropdownTrigger'))
Vue.component('fake-checkbox', require('@/components/Index/FakeCheckbox'))
Vue.component('filter-select', require('@/components/FilterSelect'))
Vue.component('filter-selector', require('@/components/FilterSelector'))
Vue.component('form-label', require('@/components/Form/Label'))
Vue.component('heading', require('@/components/Heading'))
Vue.component('icon', require('@/components/Icons/Icon'))
Vue.component('icon-edit', require('@/components/Icons/Edit'))
Vue.component('icon-delete', require('@/components/Icons/Delete'))
Vue.component('icon-download', require('@/components/Icons/Download'))
Vue.component('icon-filter', require('@/components/Icons/Filter'))
Vue.component('icon-search', require('@/components/Icons/Search'))
Vue.component('icon-view', require('@/components/Icons/View'))
Vue.component('icon-restore', require('@/components/Icons/Restore'))
Vue.component('lens-selector', require('@/components/LensSelector'))
Vue.component('loading-card', require('@/components/LoadingCard'))
Vue.component('modal', require('@/components/Modal'))
Vue.component('value-metric', require('@/components/Metrics/ValueMetric'))
Vue.component('trend-metric', require('@/components/Metrics/TrendMetric'))
Vue.component('partition-metric', require('@/components/Metrics/PartitionMetric'))
Vue.component('pagination-links', require('@/components/PaginationLinks'))
Vue.component('panel-item', require('@/components/PanelItem'))
Vue.component('resource-index', require('./views/Index'))
Vue.component('resource-panels', require('@/components/ResourcePanels'))
Vue.component('resource-table', require('@/components/ResourceTable'))
Vue.component('resource-table-row', require('@/components/Index/ResourceTableRow'))
Vue.component('search-input', require('@/components/SearchInput'))
Vue.component('validation-errors', require('@/components/ValidationErrors'))
